### ISSUE TITLE
Issues while building the reference

### ISSUE THREAD

**Issue by olgabaranov** [NKI-CCB/imfusion#3]
Hello,
while testing this tool I ran into two issues. For the first one I can make a pull request and I can add the fix for the latter problem too, but for that I am unsure what behaviour is desired. 

The first bug produces a following message 
 
```imfusion-build star     --reference_seq xxx/GRCm38.primary_assembly.genome.fa   --reference_gtf xxx/gencode.vM18.annotation.gtf     --transposon_seq /xxx/packages/imfusion-0.3.2/data/t2onc/t2onc2.sequence.fa     --transposon_features xxx/imfusion-0.3.2/data/t2onc/t2onc2.features.txt     --output_dir xxx/testingIMF     --blacklist_genes ENSMUSG00000039095 ENSMUSG00000038402     --star_threads 4
[2018-08-28 12:06:03] Copying transposon files
[2018-08-28 12:06:03] Building indexed reference gtf
[2018-08-28 12:06:54] Building flattened exon gtf
Traceback (most recent call last):
  File "xxx/miniconda3/bin/imfusion-build", line 11, in <module>
    load_entry_point('imfusion==0.3.2', 'console_scripts', 'imfusion-build')()
  File "xxx/miniconda3/lib/python3.5/site-packages/imfusion/main/build.py", line 35, in main
    output_dir=args.output_dir)
  File "xxx/miniconda3/lib/python3.5/site-packages/imfusion/build/indexers/base.py", line 178, in build
    gtf_frame_flat = tabix.flatten_gtf_frame(gtf_frame)
  File "xxx/miniconda3/lib/python3.5/site-packages/imfusion/util/tabix.py", line 239, in flatten_gtf_frame
    gtf_frame = _gtf_frame_from_exon_array(exons)
  File "xxx/miniconda3/lib/python3.5/site-packages/imfusion/util/tabix.py", line 279, in _gtf_frame_from_exon_array
    attrs = flat_exons.groupby('gene_id')['gene_id'].transform(_attribute_strs)
  File "xxx/miniconda3/lib/python3.5/site-packages/pandas/core/groupby/groupby.py", line 3663, in transform
    result = concat(results).sort_index()
  File "xxx/miniconda3/lib/python3.5/site-packages/pandas/core/reshape/concat.py", line 225, in concat
    copy=copy, sort=sort)
  File "xxx/miniconda3/lib/python3.5/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
```
Changing the regex in imfusion/util/tabix.py in lines 227 from `r'gene_id "(\w+)"'` to `'gene_id \"(\w+).+\"'` and 229 from `r'transcript_id "(\w+)"'` to `'transcript_id \"(\w+).+\"'` fixes this issue.

The second bug (or error in the documentation, I am unsure about what is desired here) arises when atempting to blacklist the genes. The genes which have the 'version number', e.g.  ENSMUSG00000039095(.8), are not found in the gtf reference by imfusion process. The example given at http://nki-ccb.github.io/imfusion/usage.html  uses the gene ID without the .8 part. When executing the command following error is reported:
```
imfusion-build star     --reference_seq xxx/GRCm38.primary_assembly.genome.fa   --reference_gtf xxx/gencode.vM18.annotation.gtf     --transposon_seq /xxx/packages/imfusion-0.3.2/data/t2onc/t2onc2.sequence.fa     --transposon_features xxx/imfusion-0.3.2/data/t2onc/t2onc2.features.txt     --output_dir xxx/testingIMF     --blacklist_genes ENSMUSG00000039095 ENSMUSG00000038402     --star_threads 4
[2018-08-28 12:15:33] Copying transposon files
[2018-08-28 12:15:33] Building indexed reference gtf
[2018-08-28 12:16:23] Building flattened exon gtf
[2018-08-28 12:17:20] Building augmented reference
> xxx/miniconda3/lib/python3.5/site-packages/imfusion/build/util.py(210)regions_from_genes()
Traceback (most recent call last):
  File "xxx/miniconda3/bin/imfusion-build", line 11, in <module>
    load_entry_point('imfusion==0.3.2', 'console_scripts', 'imfusion-build')()
  File "xxx/miniconda3/lib/python3.5/site-packages/imfusion/main/build.py", line 35, in main
    output_dir=args.output_dir)
  File "xxx/miniconda3/lib/python3.5/site-packages/imfusion/build/indexers/base.py", line 190, in build
    reference.indexed_gtf_path))
  File "xxx/miniconda3/lib/python3.5/site-packages/imfusion/build/util.py", line 210, in regions_from_genes
    raise ValueError(
ValueError: Gene 'ENSMUSG00000039095' not found in reference gtf. Make sure that the correct gene ID is being used (corresponding with the gene_id annotation in the GTF file).

```
`grep`ing it directly from file results in :
```
grep 'ENSMUSG00000039095' xxx/testingIMF/reference.gtf
chr5	HAVANA	gene	28165694	28172166	.	+	.	gene_id "ENSMUSG00000039095.8"; gene_type "protein_coding"; gene_name "En2"; level 2; havana_gene "OTTMUSG00000037277.2";
chr5	HAVANA	transcript	28165694	28172166	.	+	.gene_id "ENSMUSG00000039095.8"; transcript_id "ENSMUST00000036177.8"; gene_type "protein_coding"; gene_name "En2"; transcript_type "protein_coding"; transcript_name "RP23-358F24.1-001"; level 2; protein_id "ENSMUSP00000036761.7"; transcript_support_level "1"; tag "basic"; tag "appris_principal_1"; tag "CCDS"; ccdsid "CCDS19143.1"; havana_gene "OTTMUSG00000037277.2"; havana_transcript "OTTMUST00000096171.2";
...
```
With further testing I figured, that the blacklist gene id is tested via the `in` statement. (Line 108 in the tabix.py, `if rec['gene_id'] in sought_ids:`). Hence if the desired behaviour is to supply genes without the 'version appendix' I suggest to change the line to `if rec['gene_id'].split('.')[0] in sought_ids:` . If, on the other hand, the version appendix is needed, then changing the documentation would be helpful.

Best regards,
Olga

**Comment by jrderuiter** [comment]
Hi @Beatzekatze,

For your first issue, the regex that I use for extracting gene IDs does not account for the period in the gene names in your GTF file. The second issue is also related I think, as the proper regex should be slightly different (e.g. `'transcript_id \"([\w\.]+)"'`). 

Can you provide a link to the concerned GTF file?

Best,
Julian
